---

volumes:

  zookeeper:
  kafka:
  postgres:

services:

  zookeeper:
    image: zookeeper:3.8
    container_name: zookeeper
    hostname: zookeeper
    ports:
    - 8080:8080
    volumes:
    - zookeeper:/data
    environment:
    - TZ=America/New_York
    - ZOO_MY_ID=1
    - ZOO_SERVERS=server.1=zookeeper:2888:3888;2181
    - ZOO_STANDALONE_ENABLED=true
    - ZOO_4LW_COMMANDS_WHITELIST=*
    healthcheck:
      test: echo stat | nc zookeeper 2181
      interval: 30s
      timeout: 5s
      retries: 3

  kafka:
    image: bitnami/kafka:3.3
    container_name: kafka
    hostname: kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
    - 9094:9094
    volumes:
    - kafka:/bitnami/kafka
    environment:
    - TZ=America/New_York
    - ALLOW_PLAINTEXT_LISTENER=yes
    - KAFKA_CFG_BROKER_ID=1
    - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://:9092,EXTERNAL://${EXTERNAL_IP:-192.168.0.40}:9094
    - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9094
    - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
    - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181/kafka
    - KAFKA_CFG_ZOOKEEPER_CONNECTION_TIMEOUT_MS=60000
    - KAFKA_CFG_NUM_PARTITIONS=${MINIONS:-1}
    - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=1
    - KAFKA_CFG_MIN_INSYNC_REPLICAS=1
    - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    - KAFKA_CFG_DELETE_TOPIC_ENABLE=true
    - KAFKA_CFG_CONTROLLED_SHUTDOWN_ENABLE=true
    - KAFKA_HEAP_OPTS=-Xmx${KAFKA_HEAP:-4g} -Xms${KAFKA_HEAP:-4g} -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka -Dcom.sun.management.jmxremote.rmi.port=9999
    - JMX_PORT=9999
    healthcheck:
      test: JMX_PORT= kafka-topics.sh --list --bootstrap-server kafka:9092
      interval: 30s
      timeout: 5s
      retries: 3

  manager:
    image: hlebalbau/kafka-manager:stable
    container_name: manager
    hostname: manager
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
    - 9000:9000 
    environment:
    - TZ=America/New_York
    - ZK_HOSTS=zookeeper:2181
    healthcheck:
      test: wget --quiet --tries=1 --spider http://localhost:9000 || exit 1
      interval: 1m
      timeout: 5s
      retries: 3

  database:
    image: postgres:12
    container_name: database
    hostname: database
    volumes:
    - postgres:/var/lib/postgresql/data
    ports:
    - 5432:5432
    environment:
    - TZ=America/New_York
    - POSTGRES_HOST=database
    - POSTGRES_PORT=5432
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 5s
      retries: 3

  opennms:
    image: opennms/horizon:30.0.4
    container_name: opennms
    hostname: opennms
    depends_on:
      kafka:
        condition: service_healthy
      database:
        condition: service_healthy
    command: [ -s ]
    ports:
    - 8980:8980
    - 8101:8101
    volumes:
    - ./opennms:/opt/opennms-etc-overlay
    environment:
    - TZ=America/New_York
    - POSTGRES_HOST=database
    - POSTGRES_PORT=5432
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - JAVA_OPTS=-Xms${OPENNMS_HEAP:-4g} -Xmx${OPENNMS_HEAP:-4g} -XX:+AlwaysPreTouch -XX:+UseStringDeduplication
    healthcheck:
      test: curl -f -I http://localhost:8980/opennms/login.jsp
      interval: 1m
      timeout: 5s
      retries: 3

  emulator:
    build: .
    image: agalue/onms-minion-emulator
    container_name: emulator
    hostname: emulator
    depends_on:
    - kafka
    command:
    - -p
    - '8081'
    - -t
    - 'kafka'
    - -l
    - 'warn'
    - -u
    - 'kafka:9092'
    - -n
    - '${LOCATIONS:-100}'
    - -m
    - '${MINIONS:-1}'
    ports:
    - 8081:8081

